### ISSUE TITLE
result pagination 

### ISSUE THREAD

**Issue by beraoudabdelkhalek** [othmane099/dz-companies#1]
Add result pagination feature for the APIs. 
also, it would be better if you have uploaded the apis code for better collaboration.

**Comment by othmane099** [comment]
Salam @beraoudabdelkhalek 

Regarding your question about the API and the need for the result pagination feature, I'd like to provide some clarification. The purpose of this API is to provide a simple and general idea about the data contained in the "companies.csv" file.

Since the main goal is to offer a high-level overview of the data, the API doesn't require extensive functionality such as result pagination. Instead, it is designed to return the entire dataset in a single response.

I have no problem with uploading the code to the repository if you think it would be beneficial. Even though it's a straightforward API created for the specific purpose we discussed earlier.

**Comment by othmane099** [comment]
> Add result pagination feature for the APIs. also, it would be better if you have uploaded the apis code for better collaboration.

Salam @beraoudabdelkhalek

Regarding your question about the API and the need for the result pagination feature, I'd like to provide some clarification. The purpose of this API is to provide a simple and general idea about the data contained in the "companies.csv" file.

Since the main goal is to offer a high-level overview of the data, the API doesn't require extensive functionality such as result pagination. Instead, it is designed to return the entire dataset in a single response.

I have no problem with uploading the code to the repository if you think it would be beneficial. Even though it's a straightforward API created for the specific purpose we discussed earlier.

**Comment by beraoudabdelkhalek** [comment]
thank you for the clarification, i didn't get that from the Readme file, in this case, there is no need for uploading the code.
